"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { candidates, jobs } from "@/data/mock-data";
import { Score, StatusBadge } from "@/components/ui";

export default function CandidatesPage() {
  const [query, setQuery] = useState(""); const [role, setRole] = useState("all"); const [status, setStatus] = useState("all");
  const results = useMemo(() => candidates.filter((candidate) => (role === "all" || candidate.roleId === role) && (status === "all" || candidate.evaluationStatus === status) && candidate.name.toLowerCase().includes(query.toLowerCase())), [query, role, status]);
  return <><div className="mb-8"><p className="text-sm font-medium text-cyan-700">Candidate review</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Candidates</h1><p className="mt-2 text-slate-500">Review AI-assisted assessments and retain control over every decision.</p></div><div className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-3"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search candidates" className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-cyan-600" /><select value={role} onChange={(event) => setRole(event.target.value)} className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="all">All job postings</option>{jobs.map((job) => <option key={job.id} value={job.id}>{job.title}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="all">All evaluation statuses</option><option>Completed</option><option>Needs review</option></select></div><p className="mt-5 text-sm text-slate-500">{results.length} candidates found</p><div className="mt-3 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{results.map((candidate) => <Link href={`/candidates/${candidate.id}`} key={candidate.id} className="flex flex-wrap items-center gap-4 border-b border-slate-100 p-5 last:border-0 hover:bg-slate-50"><Score value={candidate.score} /><div className="min-w-45 flex-1"><p className="font-semibold">{candidate.name}</p><p className="mt-1 text-sm text-slate-500">{candidate.location} · Applied {candidate.appliedAt}</p></div><div className="min-w-40"><p className="text-xs text-slate-500">Evaluation</p><div className="mt-1"><StatusBadge status={candidate.evaluationStatus} /></div></div><div className="min-w-35"><p className="text-xs text-slate-500">Stage</p><p className="mt-1 text-sm font-medium">{candidate.stage}</p></div><span className="font-semibold text-cyan-700">View →</span></Link>)}</div></>;
}
