import Link from "next/link";
import { agentExecutions, candidateDetails, jobs } from "@/data/mock-data";
import { Score, StatusBadge } from "@/components/ui";

const metrics = [["Open positions", "12", "+2 this month"], ["Candidates processed", "184", "+18% this month"], ["AI evaluations completed", "163", "94% completion"], ["AI spend this month", "$428.16", "12% below plan"]];

export default function Dashboard() {
  return <>
    <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-cyan-700">Thursday, September 3</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Good afternoon, Jordan.</h1><p className="mt-2 text-slate-500">Here&apos;s what needs your attention across recruiting.</p></div><Link href="/jobs" className="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-700">+ Create job</Link></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, detail]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-2 text-xs font-medium text-emerald-600">{detail}</p></div>)}</section>
    <section className="mt-7 grid gap-7 xl:grid-cols-[1.4fr_.9fr]">
      <div className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-bold">Open positions</h2><p className="mt-1 text-sm text-slate-500">Active roles and applicant volume</p></div><Link href="/jobs" className="text-sm font-semibold text-cyan-700">View all</Link></div><div className="divide-y divide-slate-100">{jobs.filter((job) => job.status === "Published").map((job) => <Link href={`/jobs/${job.id}`} key={job.id} className="flex items-center justify-between gap-4 p-5 hover:bg-slate-50"><div><p className="font-semibold">{job.title}</p><p className="mt-1 text-sm text-slate-500">{job.department} · {job.location.displayName}</p></div><div className="flex items-center gap-4"><span className="text-sm text-slate-500">{job.applicantCount} applicants</span><StatusBadge status={job.status} /></div></Link>)}</div></div>
      <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Recent activity</h2><div className="mt-4 space-y-5">{agentExecutions.map((run) => <div key={run.id} className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{run.agentName}</p><p className="mt-1 text-xs text-slate-500">{run.model} · {new Date(run.startedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p></div><StatusBadge status={run.status} /></div>)}</div><Link href="/operations" className="mt-6 block text-sm font-semibold text-cyan-700">Open operations center →</Link></div>
    </section>
    <section className="mt-7 rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-bold">Candidates needing attention</h2><p className="mt-1 text-sm text-slate-500">AI evidence ready for accountable human review</p></div><Link href="/candidates" className="text-sm font-semibold text-cyan-700">View all</Link></div><div className="grid gap-4 p-5 md:grid-cols-3">{candidateDetails.slice(0, 3).map(({ candidate, evaluation, report }) => <Link key={candidate.id} href={`/candidates/${candidate.id}`} className="rounded-lg border border-slate-200 p-4 hover:bg-slate-50"><div className="flex items-center justify-between"><Score value={report.overallScore} /><StatusBadge status={evaluation.status} /></div><p className="mt-3 font-semibold">{candidate.firstName} {candidate.lastName}</p><p className="mt-1 text-sm text-slate-500">{report.recommendation}</p></Link>)}</div></section>
  </>;
}
