import Link from "next/link";
import { notFound } from "next/navigation";
import { candidates, jobs } from "@/data/mock-data";
import { Score, StatusBadge } from "@/components/ui";

export function generateStaticParams() { return candidates.map(({ id }) => ({ id })); }
export default async function CandidateDetails({ params }: { params: Promise<{ id: string }> }) {
  const candidate = candidates.find((item) => item.id === (await params).id); if (!candidate) notFound(); const job = jobs.find((item) => item.id === candidate.roleId);
  return <><Link href="/candidates" className="text-sm font-semibold text-cyan-700">← All candidates</Link><div className="mt-5 flex flex-wrap items-center gap-4"><Score value={candidate.score} /><div><h1 className="text-3xl font-bold tracking-tight">{candidate.name}</h1><p className="mt-1 text-slate-500">{job?.title} · {candidate.location}</p></div><div className="ml-auto"><StatusBadge status={candidate.evaluationStatus} /></div></div><div className="mt-7 grid gap-6 lg:grid-cols-[.8fr_1.4fr]"><aside className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">Candidate profile</h2><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-slate-500">Email</dt><dd className="mt-1 font-medium">{candidate.email}</dd></div><div><dt className="text-slate-500">Applied</dt><dd className="mt-1 font-medium">{candidate.appliedAt}</dd></div><div><dt className="text-slate-500">Current stage</dt><dd className="mt-1 font-medium">{candidate.stage}</dd></div></dl><h3 className="mt-8 font-bold">Recruiter feedback</h3><textarea className="mt-3 h-24 w-full rounded-lg border border-slate-200 p-3 text-sm" placeholder="Add private feedback…" /><button className="mt-3 w-full rounded-lg border border-slate-300 py-2.5 text-sm font-semibold">Save feedback</button></aside><div className="space-y-6"><section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">Resume summary</h2><p className="mt-4 leading-7 text-slate-700">{candidate.resumeSummary}</p></section><section className="rounded-xl border border-cyan-100 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-cyan-700">AI-generated evaluation report</p><h2 className="mt-1 text-xl font-bold">Suitability score: {candidate.score}/100</h2></div><StatusBadge status={candidate.evaluationStatus} /></div><p className="mt-5 font-medium text-slate-700">{candidate.recommendation}</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><div><h3 className="font-semibold text-emerald-700">Evidence strengths</h3><ul className="mt-3 space-y-2 text-sm text-slate-600">{candidate.strengths.map((item) => <li key={item}>✓ {item}</li>)}</ul></div><div><h3 className="font-semibold text-amber-700">Considerations</h3><ul className="mt-3 space-y-2 text-sm text-slate-600">{candidate.considerations.map((item) => <li key={item}>• {item}</li>)}</ul></div></div><p className="mt-6 border-t border-slate-100 pt-4 text-xs text-slate-500">Candidate evaluation agent · gpt-4.1 · Run run_84f2a · Evaluation policy v1.4</p></section></div></div></>;
}
